from enum import IntEnum
from typing import Callable, Dict, List, Optional

def init(shaderDir: str, toonDir: str, blinkMorphs: Optional[List[str]] = ...) -> None: ...
def glInit() -> None: ...
def dispose() -> None: ...
def initArgs() -> Dict[str, object]: ...

class CameraMode(IntEnum):
    FPS: int  # 0
    Orbit: int  # 1

class Camera:
    x: float
    y: float
    z: float
    rotX: float
    rotY: float
    speed: float

    # Orbit mode state
    mode: CameraMode
    targetX: float
    targetY: float
    targetZ: float
    orbitDistance: float
    orbitLatitude: float
    orbitLongitude: float
    orbitFov: float

    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def update(self, dt: float, w: bool, a: bool, s: bool, d: bool, e: bool, q: bool) -> None: ...
    def onMouseButton(self, *args: bool | int) -> None: ...
    def onCursorPos(self, xpos: float, ypos: float) -> None: ...
    def onScroll(self, yoffset: float) -> None: ...
    def viewMatrix(self) -> List[float]: ...
    @staticmethod
    def projectionMatrix(width: int, height: int, fov: float = ..., nearPlane: float = ..., farPlane: float = ...) -> List[float]: ...
    def toggleMode(self) -> None: ...

class Model:
    def __init__(self) -> None: ...
    
    def load(self, path: str) -> None: ...
    def update(self, dt: float) -> None: ...
    def draw(self, width: int, height: int) -> None: ...
    
    def enablePhysics(self, on: bool) -> None: ...
    def physicsEnabled(self) -> bool: ...
    def showRigidBodies(self, v: bool) -> None: ...
    
    def loadVmd(self, path: str) -> int: ...
    def playVmd(self, trackId: int, onEnd: Optional[Callable[[int], None]] = ...) -> None: ...
    def pauseVmd(self, trackId: int) -> None: ...
    def stopVmd(self, trackId: int) -> None: ...
    def removeVmd(self, trackId: int) -> None: ...
    def playAllVmd(self) -> None: ...
    def pauseAllVmd(self) -> None: ...
    def stopAllVmd(self) -> None: ...
    def isVmdPlaying(self) -> bool: ...
    def vmdTrackCount(self) -> int: ...
    def isVmdPlayingTrack(self, trackId: int) -> bool: ...
    def vmdCurrentFrame(self, trackId: int) -> float: ...
    def vmdMaxFrame(self, trackId: int) -> float: ...
    def setVmdFrame(self, trackId: int, frame: float) -> None: ...
    
    def loadVpd(self, path: str) -> int: ...
    def applyVpd(self, vpdId: int) -> None: ...
    def resetPose(self) -> None: ...
    def syncVpdPose(self) -> None: ...
    def vpdApplied(self) -> bool: ...
    def removeVpd(self, vpdId: int) -> None: ...
    
    def showModel(self, v: bool) -> None: ...
    def showOutline(self, v: bool) -> None: ...
    def showToon(self, v: bool) -> None: ...
    def getShowModel(self) -> bool: ...
    def getShowOutline(self) -> bool: ...
    def getShowToon(self) -> bool: ...
    def isSkinned(self) -> bool: ...
    def setSkinning(self, on: bool) -> None: ...
    
    def setMorphWeight(self, name: str, weight: float) -> None: ...
    def savedMorphWeight(self, name: str) -> float: ...
    def clearMorphs(self) -> None: ...
    def setMorphWeights(self, weights: Dict[str, float]) -> None: ...
    def setIdleBlink(self, on: bool) -> None: ...
    def morphCount(self) -> int: ...
    def interactableMorphs(self) -> List[int]: ...
    def morphName(self, index: int) -> str: ...
    
    def lookAt(self, x: int, y: int, w: int, h: int) -> None: ...
    def resetLookAt(self) -> None: ...

    def modelName(self) -> str: ...
    def modelScale(self) -> float: ...
    def modelMatrix(self) -> List[float]: ...
