name: Linux

on:
  push:
    tags:
      - "v*.*.*"
    branches: [ linux-workflow, build-all ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build (GCC)
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev \
            libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Configure
        run: cmake -B build -DBUILD_VIEWER=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build
        run: cmake --build build

      - name: Upload viewer
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: build/viewer/viewer
